version: "3.7"

services:
  web:
    image: docker.pkg.github.com/arwynfr/homepage/homepage:master
    networks:
      - reverse
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.homepage.loadBalancer.server.port=80"
        - "traefik.http.routers.homepage.entrypoints=http"
        - "traefik.http.routers.homepage.rule=Host(`www.arwyn.fr`)"
        - "traefik.http.routers.homepage.middlewares=https@file"
        - "traefik.http.routers.homepage_tls.entrypoints=https"
        - "traefik.http.routers.homepage_tls.rule=Host(`www.arwyn.fr`)"
        - "traefik.http.routers.homepage_tls.tls.options=secure@file"
        - "traefik.http.routers.homepage_tls.tls.certResolver=gandi"
        - "traefik.http.routers.homepage_tls.service=homepage"

networks:
  reverse:
    external: true
