name: continuous-deployment

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source files
        uses: actions/checkout@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
          repository: arwynfr/stack-homepage/homepage
          tag_with_ref: true
          tag_with_sha: true
          tags: master
          path: ./src

      - name: Deploy stack
        env:
          DOCKER_CACERT: ${{ secrets.DOCKER_CACERT }}
          DOCKER_CERT: ${{ secrets.DOCKER_CERT }}
          DOCKER_KEY: ${{ secrets.DOCKER_KEY }}
          DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
          DOCKER_TLS_VERIFY: 1
        run: |
          mkdir --parents ~/.docker
          echo "$DOCKER_CACERT" > ~/.docker/ca.pem
          echo "$DOCKER_CERT" > ~/.docker/cert.pem
          echo "$DOCKER_KEY" > ~/.docker/key.pem
          docker stack rm homepage
          docker stack deploy --prune --compose-file ./stack/docker-compose.yml homepage
