name: CICD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source files
        uses: actions/checkout@v1

      - name: Build the Docker image
        run: |
          docker build ./src --file ./src/Dockerfile \
            --tag docker.pkg.github.com/arwynfr/homepage/homepage:$(date +%s) \
            --tag docker.pkg.github.com/arwynfr/homepage/homepage:git-$(git rev-parse --short "$GITHUB_SHA") \
            --tag docker.pkg.github.com/arwynfr/homepage/homepage:master

      - name: Push image to Github Packages
        run: |
          docker login docker.pkg.github.com --username arwynfr --password ${{ secrets.GITHUB_TOKEN }}
          docker push docker.pkg.github.com/arwynfr/homepage/homepage
          
      - name: Copy stack file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "./stack/*"
          target: "~/stacks/homepage"
          overwrite: true
          strip_components: 1

      - name: Update stack
        uses: appleboy/ssh-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: GITHUB_TOKEN
          script: |
            docker login docker.pkg.github.com --username arwynfr --password $GITHUB_TOKEN
            docker pull docker.pkg.github.com/arwynfr/homepage/homepage:master
            docker stack rm homepage
            docker stack deploy -c ~/stacks/homepage/docker-compose.yml homepage

