name: Build docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source files
        uses: actions/checkout@v1
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile \
            --tag docker.pkg.github.com/arwynfr/homepage/homepage:$(date +%s) \
            --tag docker.pkg.github.com/arwynfr/homepage/homepage:git-$(git rev-parse --short "$GITHUB_SHA") \
            --tag docker.pkg.github.com/arwynfr/homepage/homepage:master
      - name: Push image to Github Packages
        run: docker push docker.pkg.github.com/arwynfr/homepage/homepage
