name: CICD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source files
        uses: actions/checkout@v1

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile \
            --tag docker.pkg.github.com/arwynfr/homepage/homepage:$(date +%s) \
            --tag docker.pkg.github.com/arwynfr/homepage/homepage:git-$(git rev-parse --short "$GITHUB_SHA") \
            --tag docker.pkg.github.com/arwynfr/homepage/homepage:master

      - name: Push image to Github Packages
        run: |
          docker login docker.pkg.github.com --username arwynfr --password ${{ secrets.GITHUB_TOKEN }}
          docker push docker.pkg.github.com/arwynfr/homepage/homepage

  deploy:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout source files
        uses: actions/checkout@v1

      - name: Copy stack file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml"
          target: "~/stacks/homepage"
          overwrite: true
    
      - name: Update stack
        uses: appleboy/ssh-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: ~/stacks/update-stack.sh homepage
          envs: GITHUB_TOKEN