name: continuous-deployment

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source files
        uses: actions/checkout@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
          repository: arwynfr/stack-homepage/homepage
          tag_with_ref: true
          tag_with_sha: true
          tags: master
          path: ./src

      - name: Deploy stack
        env:
          DOCKER_HOST: ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}          
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          ssh-add <(echo "$SSH_KEY")
          docker stack rm homepage
          docker stack deploy --prune --compose-file ./stack/docker-compose.yml homepage
