name: Publish stack to production

on:
  registry_package:

jobs:
  
  deploy:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@master
      
      - name: Copy stack file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml"
          target: "~/stacks/homepage"
          overwrite: true
    
      - name: Update stack
        uses: appleboy/ssh-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: ~/stacks/update-stack.sh homepage
          envs: GITHUB_TOKEN
    
